### ISSUE TITLE
[BUG] There is some problem when passing the query to the tool

### ISSUE THREAD

**Issue by danielzzz** [opensearch-project/opensearch-mcp-server-py#141]
### What is the bug?
I am using this from cursor, trying to get some data from elastic search server. 

I am getting this comment:
{"query": {"range": {"entity_id": {"gte": 390000, "lte": 400000}}}, "size": 1}
The tool appears to be receiving an incomplete/malformed query string, so the filter isn't applied. The results show:
Total hits: 6,143 (all documents in the index)
Returned documents have entity_id: 3339 (not in the requested range)
The query filter is not being applied
This looks like a tool limitation where the query parameter isn't handling the JSON string correctly. The query should filter for entity_id between 390000 and 400000 and return only 1 result, but it's returning all documents instead.

when I try to run the same query on the server from curl, I do get the correct result:
curl -X POST "http://host.docker.internal:9200/my-index/_search" \
  -H "Content-Type: application/json" \
  -d '{"query": {"range": {"entity_id": {"gte": 390000, "lte": 400000}}}, "size": 1}'

so it seems to me, there must be some problem between cursor and the tool. 
have you seen something like this?

**Comment by narcisond35-svg** [comment]
This should solve the problem.
[e944c7e924dd.zip](https://github.com/user-attachments/files/23679906/e944c7e924dd.zip)

**Comment by nathaliellenaa** [comment]
Hi @danielzzz , I'm trying to reproduce the issue on my end. Can you share more details to reproduce this issue (e.g., the opensearch-mcp-server-py version, sample prompt/query that was sent to the agent, is this issue persistent)? I tested using the latest 0.6.0 version, and couldn't reproduce the same issue

**Example:**
Prompt that was sent to the agent:
```
Search for documents in my-index where entity_id is between 390000 and 400000, return 1 result
```

Response:

<img width="724" height="503" alt="Image" src="https://github.com/user-attachments/assets/143307ee-cb49-4493-91e2-54429ab264ce" />
